"""
Combinations Models - Trading strategy combinations.

This module provides models for:
- Combination: Definition of the 8 trading combinations
- CombinationResult: Evaluation results for each combination
"""

from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.core.models import BaseModel, SignalDirectionMixin
from apps.market_data.models import TradingPair


class Combination(BaseModel):
    """
    Defines the 8 trading combinations.

    Each combination uses a specific set of indicators
    with defined entry/exit rules.
    """
    COMBO_GOLDEN_CONFLUENCE = 'golden_confluence'
    COMBO_MEAN_REVERSION = 'mean_reversion'
    COMBO_BREAKOUT_MOMENTUM = 'breakout_momentum'
    COMBO_HARMONIC_CONFLUENCE = 'harmonic_confluence'
    COMBO_LINEAR_REGRESSION = 'linear_regression_channel'
    COMBO_MULTI_TIMEFRAME = 'multi_timeframe'
    COMBO_STOCHASTIC_CROSSOVER = 'stochastic_crossover'
    COMBO_ULTIMATE_CONFLUENCE = 'ultimate_confluence'

    COMBINATION_CHOICES = [
        (COMBO_GOLDEN_CONFLUENCE, _('Golden Confluence')),
        (COMBO_MEAN_REVERSION, _('Mean Reversion Power')),
        (COMBO_BREAKOUT_MOMENTUM, _('Breakout Momentum Hunter')),
        (COMBO_HARMONIC_CONFLUENCE, _('Harmonic Confluence')),
        (COMBO_LINEAR_REGRESSION, _('Linear Regression Channel')),
        (COMBO_MULTI_TIMEFRAME, _('Multi-Timeframe Convergence')),
        (COMBO_STOCHASTIC_CROSSOVER, _('Stochastic Crossover System')),
        (COMBO_ULTIMATE_CONFLUENCE, _('Ultimate Confluence')),
    ]

    name = models.CharField(
        max_length=50,
        choices=COMBINATION_CHOICES,
        unique=True,
        verbose_name=_('Name')
    )
    display_name = models.CharField(
        max_length=100,
        verbose_name=_('Display Name')
    )
    description = models.TextField(
        blank=True,
        verbose_name=_('Description')
    )
    win_rate = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name=_('Win Rate (%)'),
        help_text=_('Historical win rate percentage')
    )
    risk_reward_ratio = models.DecimalField(
        max_digits=4,
        decimal_places=1,
        verbose_name=_('Risk/Reward Ratio'),
        help_text=_('Expected risk/reward ratio')
    )
    required_indicators = models.JSONField(
        default=list,
        verbose_name=_('Required Indicators'),
        help_text=_('List of indicator names required')
    )
    entry_rules = models.JSONField(
        default=dict,
        verbose_name=_('Entry Rules'),
        help_text=_('Buy and sell entry criteria')
    )
    exit_rules = models.JSONField(
        default=dict,
        verbose_name=_('Exit Rules'),
        help_text=_('Stop loss and take profit rules')
    )
    optimal_conditions = models.JSONField(
        default=dict,
        verbose_name=_('Optimal Conditions'),
        help_text=_('Market conditions where this combination performs best')
    )
    is_enabled = models.BooleanField(
        default=True,
        verbose_name=_('Is Enabled')
    )

    class Meta:
        db_table = 'combinations_combination'
        verbose_name = _('Combination')
        verbose_name_plural = _('Combinations')
        ordering = ['name']

    def __str__(self):
        return f"{self.display_name} ({self.win_rate}%)"


class CombinationResult(BaseModel, SignalDirectionMixin):
    """
    Result of evaluating a combination for a specific moment.

    Stores the signal generated by each combination along with
    the indicator values and confidence score.
    """
    combination = models.ForeignKey(
        Combination,
        on_delete=models.CASCADE,
        related_name='results',
        verbose_name=_('Combination')
    )
    trading_pair = models.ForeignKey(
        TradingPair,
        on_delete=models.CASCADE,
        related_name='combination_results',
        verbose_name=_('Trading Pair')
    )
    timeframe = models.CharField(
        max_length=10,
        verbose_name=_('Timeframe')
    )
    timestamp = models.DateTimeField(
        verbose_name=_('Timestamp')
    )
    confidence_score = models.IntegerField(
        default=0,
        verbose_name=_('Confidence Score'),
        help_text=_('Score 0-100 based on criteria met')
    )
    indicator_values = models.JSONField(
        default=dict,
        verbose_name=_('Indicator Values'),
        help_text=_('Snapshot of indicator values used')
    )
    criteria_met = models.JSONField(
        default=dict,
        verbose_name=_('Criteria Met'),
        help_text=_('Which criteria were met/failed')
    )
    notes = models.TextField(
        blank=True,
        verbose_name=_('Notes')
    )

    class Meta:
        db_table = 'combinations_result'
        verbose_name = _('Combination Result')
        verbose_name_plural = _('Combination Results')
        indexes = [
            models.Index(fields=['trading_pair', 'timestamp']),
            models.Index(fields=['combination', 'timestamp']),
        ]
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.combination.name} - {self.trading_pair.symbol} - {self.signal}"
